# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pymp3_c')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pymp3_c')
    _pymp3_c = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pymp3_c', [dirname(__file__)])
        except ImportError:
            import _pymp3_c
            return _pymp3_c
        try:
            _mod = imp.load_module('_pymp3_c', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _pymp3_c = swig_import_helper()
    del swig_import_helper
else:
    import _pymp3_c
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class LameDecoder(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LameDecoder, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LameDecoder, name)
    __repr__ = _swig_repr
    __swig_setmethods__["gfp"] = _pymp3_c.LameDecoder_gfp_set
    __swig_getmethods__["gfp"] = _pymp3_c.LameDecoder_gfp_get
    if _newclass:
        gfp = _swig_property(_pymp3_c.LameDecoder_gfp_get, _pymp3_c.LameDecoder_gfp_set)

    def __init__(self):
        this = _pymp3_c.new_LameDecoder()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pymp3_c.delete_LameDecoder
    __del__ = lambda self: None

    def decode_frame(self, mp3buf, begin, len, total_read, pcm_l, pcm_r):
        return _pymp3_c.LameDecoder_decode_frame(self, mp3buf, begin, len, total_read, pcm_l, pcm_r)
LameDecoder_swigregister = _pymp3_c.LameDecoder_swigregister
LameDecoder_swigregister(LameDecoder)


def interlace_array(uc_left, uc_right, uc_joined, num_samples):
    return _pymp3_c.interlace_array(uc_left, uc_right, uc_joined, num_samples)
interlace_array = _pymp3_c.interlace_array
# This file is compatible with both classic and new-style classes.


